# Generated by Django 4.0 on 2022-01-05 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lekarze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
                ('tytul_nauk', models.CharField(max_length=30)),
                ('specjalizacja_naukowa', models.CharField(choices=[('Chi', 'Chirurg'), ('Ort', 'Ortopeda'), ('Ogl', 'Ogolne'), ('Kar', 'Kardiolog')], max_length=3)),
                ('specjalizacja_leczenia', models.CharField(choices=[('Pie', 'Psy'), ('Kot', 'Koty'), ('MSa', 'Male ssaki'), ('DSa', 'Duze ssaki'), ('Gad', 'Gady'), ('Pta', 'Ptaki')], max_length=3)),
                ('opis_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Lekarz',
                'verbose_name_plural': 'Lekarze',
                'ordering': ['nazwisko'],
            },
        ),
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
                ('imie_zwierza', models.CharField(max_length=30)),
                ('rodzaj_zwierza', models.CharField(choices=[('Pie', 'Psy'), ('Kot', 'Koty'), ('MSa', 'Male ssaki'), ('DSa', 'Duze ssaki'), ('Gad', 'Gady'), ('Pta', 'Ptaki'), ('Inn', 'Inne')], max_length=3)),
                ('phone_number', models.CharField(max_length=12, verbose_name='Numer telefonu')),
                ('address', models.CharField(max_length=256, verbose_name='Adres')),
                ('description', models.CharField(max_length=516, verbose_name='Powod wizyty')),
                ('email_address', models.EmailField(max_length=150)),
            ],
            options={
                'verbose_name': 'Pacjent',
                'verbose_name_plural': 'Pacjenci',
                'ordering': ['nazwisko'],
            },
        ),
        migrations.CreateModel(
            name='Wizyta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wizyta_data', models.DateField(blank=True, null=True, verbose_name='Data wizyty')),
                ('wizyta_time', models.TimeField(blank=True, null=True, verbose_name='Godzina wizyty')),
                ('wizyta_lekarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.lekarze', verbose_name='Lekarz')),
                ('wizyta_pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pacjent', verbose_name='Pacjent')),
            ],
            options={
                'verbose_name': 'Wizyta',
                'verbose_name_plural': 'Wizyty',
                'ordering': ['wizyta_data'],
            },
        ),
    ]
