# Generated by Django 4.0.1 on 2022-01-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_lekarze_pacjent_wizyta_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizyta',
            name='wizyta_data',
            field=models.DateTimeField(null=True, verbose_name='Data wizyty'),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='wizyta_time',
            field=models.TimeField(null=True, verbose_name='Godzina wizyty'),
        ),
    ]
